app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

from app.models import User

class CreatePostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

app/main/routes.py
from flask import render_template, request, Blueprint, g, current_app, url_for
from flask_login import login_required, current_user

from app.models import Post
from app.main.forms import SearchForm
import os

# main blueprint
main = Blueprint('main', __name__)

@main.before_app_request
def before_request():
    if current_user.is_authenticated:
        '''
            This g variable provided by Flask is a place where the application can store data
            that needs to persist through the life of a request.
        '''
        g.search_form = SearchForm()

@main.route('/')
@main.route('/home')
def home():
    page_no = request.args.get('page', 1, type=int)
    all_posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page_no, per_page=current_app.config['POSTS_PER_PAGE'])
    return render_template('home.html', posts=all_posts)

@main.route('/about')
def about():
    return render_template('about.html', title='About')

@main.route('/search')
@login_required
def search():

    if not g.search_form.validate():
        return redirect(url_for('main.home'))

    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])

    next_url = url_for('main.search', q=g.search_form.q.data, page=page+1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None

    prev_url = url_for('main.search', q=g.search_form.q.data, page=page-1) \
        if page > 1 else None
    
    return render_template('search.html', title='Search', posts=posts, next_url=next_url, prev_url=prev_url)

app/posts/routes.py
from flask import render_template, url_for, flash, redirect, abort, Blueprint
from flask_login import current_user, login_required

from app import db
from app.posts.forms import CreatePostForm
from app.models import Post

# posts blueprint
posts = Blueprint('posts', __name__)

@posts.route('/create-post', methods=['GET', 'POST'])
@login_required
def create_post():
    form = CreatePostForm()

    if form.validate_on_submit():
        flash('Your post has been created!', 'success')
        new_post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(new_post)
        db.session.commit()

        return redirect(url_for('main.home'))

    return render_template('create_post.html', title='New Post', form=form, legend='Create Post')

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title={post.title}, post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        abort(403)
    
    form = CreatePostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()

        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    
    form.title.data = post.title
    form.content.data = post.content
    
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash("You post has been deleted", 'success')
    
    return redirect(url_for('main.home'))

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, logout_user, current_user, login_required

from app import db, bcrypt
from app.users.forms import RegistrationForm, LoginForm, AccountUpdateForm, \
    RequestResetForm, ResetPasswordForm
from app.models import User, Post
from app.users.utils import save_picture, send_password_reset_email

# creating a users blueprint
users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    
        new_user = User(username=form.username.data, email=form.email.data, password=hashed_pwd)
        db.session.add(new_user)
        db.session.commit()

        flash(f'Your account has been created, You will be able to login now!', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title="Register", form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Login Unsuccessful, Please try again', 'danger')

    return render_template('login.html', title="Login", form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = AccountUpdateForm()
    
    if form.validate_on_submit():
        if form.pfp.data:
            pfp_filename = save_picture(form.pfp.data, form.username.data)
            current_user.image_file = pfp_filename

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash(f'Your account info has been updated', 'success')
        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    pfp_url = url_for('static', filename=f"images/profile_imgs/{current_user.image_file}")
    return render_template('account.html', title='Account', pfp_url=pfp_url, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    page_no = request.args.get('page', 1, type=int)
    
    # getting user
    user = User.query.filter_by(username=username).first_or_404()
    
    # getting all the posts by that user
    user_posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page_no, per_page=current_app.config['POSTS_PER_PAGE'])
    
    return render_template('user_posts.html', posts=user_posts, user=user)

@users.route('/reset-password', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RequestResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_password_reset_email(user)
        flash('Please check your email for instructions to reset your password!', 'info')
        return redirect(url_for('users.login'))

    return render_template('request_reset_password.html', title="Request Reset password", form=form)

@users.route('/reset-password<string:token>', methods=['GET', 'POST'])
def reset_password_token(token):
    if current_user.is_authenticated:
         return redirect(url_for('main.home'))
    
    user = User.verify_reset_token(token)
    if not user:
        flash("The token is either Invalid or expired", "warning")
        return redirect(url_for('users.reset_password_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    
        user.password = hashed_pwd
        db.session.commit()

        flash(f'Your account\'s password has been updated, Please login to continue', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password.html', title="Reset password", user=user)

app/templates/about.html
{%  extends 'layout.html' %}

{% block content %}
    <h1>About Page</h1>
{% endblock content %}

app/templates/account.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ pfp_url }}" alt="pfp-{{current_user.username}}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <form method="POST" action="" novalidate enctype="multipart/form-data">
            
            {{ form.hidden_tag() }} <!-- Adds a CSRF token -->
            
            <fieldset class="form-group">
                
                <legend class="border-bottom mb-4">Update Account Info</legend>
                
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class='invalid-feedback'>
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}    
                    {% endif %}
                </div>
                
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class='invalid-feedback'>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}    
                    {% endif %}
                </div>

                <div class="form-group mt-3">
                    {{ form.pfp.label() }}
                    </br>
                    <div class="mt-2">
                        {{ form.pfp(class="form-control-file") }}
                    </div>
                        {% if form.pfp.errors %}
                        {% for error in form.pfp.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %} 
                    {% endif %}
                </div>
                
            </fieldset>

            <div class="form-group mt-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

        </form>
    </div>

{% endblock content%}

app/templates/create_post.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group mt-4">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <img
                        class="rounded-circle article-img"
                        src="{{ url_for('static', filename='images/profile_imgs/' + post.author.image_file ) }}"
                        alt="pfp-{{ post.author.username }}"
                    />
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
      </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if page_num == posts.page %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}" >{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}" >{{ page_num }}</a>
            {% endif %}    
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}" />

    {% if title %}
        <title>Blog App - {{ title }}</title>
    {% else %}
        <title>Blog App</title>
    {% endif %}
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{url_for('main.home')}}">My Blog App</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                {% if g.search_form %}
                  <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
                      <div class="form-group">
                          {{ g.search_form.q(size=20, class='form-control',
                              placeholder=g.search_form.q.label.text) }}
                      </div>
                  </form>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('posts.create_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}"> Account </a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}"> Logout </a>                      
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          
          <!-- displaying flash messages similar to that of toast -->
          {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  {% for category, message in messages%}
                      <div class="alert alert-{{ category }}">
                          {{ message }}
                      </div>
                  {% endfor %}
              {% endif %}
          {% endwith %}
          
          <!-- CONTENT BLOCK -->
          {% block content %}{% endblock %}
          <!-- CONTENT BLOCK ENDS-->

        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Quick Links</h3>
            <p class='text-muted'>Checkout below links:
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

</body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check mt-2">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-1">
                    <a href="{{ url_for('users.reset_password_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-2">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

app/templates/post.html
{% extends 'layout.html' %}

{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <img
                    class="rounded-circle article-img"
                    src="{{ url_for('static', filename='images/profile_imgs/' + post.author.image_file ) }}"
                    alt="pfp-{{ post.author.username }}"
                />
                <a class="m-2" href="#">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button
                            type="button"
                            class="btn btn-danger btn-sm m-1"
                            data-bs-toggle="modal"
                            data-bs-target="#delete-modal"
                        >
                            Delete
                        </button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>

    <!-- Delete Post Confirmation Modal -->
    <div class="modal fade" id="delete-modal" tabindex="-1" aria-labelledby="delete-modal-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="delete-modal-label">Delete Post</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete"/>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/request_reset_password.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Forgot Password</legend>
                <p>Enter email to get the reset password link.</p>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>  
{% endblock content %}

app/templates/reset_password.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                
            </fieldset>
            
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}

                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class='invalid-feedback'>
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}    
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}

                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class='invalid-feedback'>
                    {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}    
                {% endif %}
            </div>

            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>  
{% endblock content %}

app/templates/search.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Search Results</h1>
    {% for post in posts %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <img
                        class="rounded-circle article-img"
                        src="{{ url_for('static', filename='images/profile_imgs/' + post.author.image_file ) }}"
                        alt="pfp-{{ post.author.username }}"
                    />
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>
                    Previous results
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Next results
                    <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock content %}

app/templates/user_posts.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="mb-3">Posts by: {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <img
                        class="rounded-circle article-img"
                        src="{{ url_for('static', filename='images/profile_imgs/' + post.author.image_file ) }}"
                        alt="pfp-{{ post.author.username }}"
                    />
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
      </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if page_num == posts.page %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" >{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" >{{ page_num }}</a>
            {% endif %}    
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}